#!/bin/bash
## this is not a real service, just a helper script for admins
## to restart things in the proper order

function status() {
    service gmetad status
    service gmondsrv status
    service rrdcached status
}

function start() {
    service rrdcached start
    service gmondsrv start
    service gmetad start
}
function stop() {
    service gmondsrv stop
    service gmetad stop
    service rrdcached stop
}
function reload() {
    service gmetad stop
    service gmondsrv stop
    service gmondsrv start
    service gmetad start
}


function help() {
    echo "service ganglia {status|start|stop|restart|reload}"
    echo "  - reload is sufficient to cleanup stale hosts from Ganglia, it will not restart rrdcached"
    echo "  - restart will also restart rrdcached"
}

case $1 in
status)  status;;
start)   start;;
stop)    stop;;
restart) stop;start;;
*) help;;
esac
    